
name: Release
on:
  schedule:
    - cron: "45 */12 * * *"
  push:
    branches:
      - "main"


jobs:
  Telegram:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@latest

    - name: Download Telegram
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        chmod +x build.sh
        ./build.sh


    - name: Upload artifact
      uses: actions/upload-artifact@latest
      with:
        name: telegram-continuous.AppImage
        path: 'dist'

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Telegram AppImage ${{ env.TELEGRAM_VERSION }} Build
        automatic_release_tag: ${{ env.TELEGRAM_VERSION }}
        prerelease: false
        files: |
          dist/
        repo_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Release Continuous
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Telegram AppImage Continuous Build
        automatic_release_tag: continuous
        prerelease: true
        files: |
          dist/
        repo_token: ${{ secrets.GITHUB_TOKEN }}
